// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.36.0
// source: fractal.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "fractal";

export interface FractalRequest {
  kind: number;
  maxIterations: number;
  xMin: number;
  xMax: number;
  yMin: number;
  yMax: number;
}

export interface Point {
  x: number;
  y: number;
  intensity: number;
}

export interface FractalResponse {
  points: Point[];
}

function createBaseFractalRequest(): FractalRequest {
  return { kind: 0, maxIterations: 0, xMin: 0, xMax: 0, yMin: 0, yMax: 0 };
}

export const FractalRequest: MessageFns<FractalRequest> = {
  encode(message: FractalRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.kind !== 0) {
      writer.uint32(8).int32(message.kind);
    }
    if (message.maxIterations !== 0) {
      writer.uint32(16).int32(message.maxIterations);
    }
    if (message.xMin !== 0) {
      writer.uint32(25).double(message.xMin);
    }
    if (message.xMax !== 0) {
      writer.uint32(33).double(message.xMax);
    }
    if (message.yMin !== 0) {
      writer.uint32(41).double(message.yMin);
    }
    if (message.yMax !== 0) {
      writer.uint32(49).double(message.yMax);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FractalRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFractalRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.kind = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.maxIterations = reader.int32();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.xMin = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.xMax = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.yMin = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.yMax = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): FractalRequest {
    return {
      kind: isSet(object.kind) ? globalThis.Number(object.kind) : 0,
      maxIterations: isSet(object.maxIterations)
        ? globalThis.Number(object.maxIterations)
        : isSet(object.max_iterations)
        ? globalThis.Number(object.max_iterations)
        : 0,
      xMin: isSet(object.xMin)
        ? globalThis.Number(object.xMin)
        : isSet(object.x_min)
        ? globalThis.Number(object.x_min)
        : 0,
      xMax: isSet(object.xMax)
        ? globalThis.Number(object.xMax)
        : isSet(object.x_max)
        ? globalThis.Number(object.x_max)
        : 0,
      yMin: isSet(object.yMin)
        ? globalThis.Number(object.yMin)
        : isSet(object.y_min)
        ? globalThis.Number(object.y_min)
        : 0,
      yMax: isSet(object.yMax)
        ? globalThis.Number(object.yMax)
        : isSet(object.y_max)
        ? globalThis.Number(object.y_max)
        : 0,
    };
  },

  toJSON(message: FractalRequest): unknown {
    const obj: any = {};
    if (message.kind !== 0) {
      obj.kind = Math.round(message.kind);
    }
    if (message.maxIterations !== 0) {
      obj.maxIterations = Math.round(message.maxIterations);
    }
    if (message.xMin !== 0) {
      obj.xMin = message.xMin;
    }
    if (message.xMax !== 0) {
      obj.xMax = message.xMax;
    }
    if (message.yMin !== 0) {
      obj.yMin = message.yMin;
    }
    if (message.yMax !== 0) {
      obj.yMax = message.yMax;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FractalRequest>, I>>(base?: I): FractalRequest {
    return FractalRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FractalRequest>, I>>(object: I): FractalRequest {
    const message = createBaseFractalRequest();
    message.kind = object.kind ?? 0;
    message.maxIterations = object.maxIterations ?? 0;
    message.xMin = object.xMin ?? 0;
    message.xMax = object.xMax ?? 0;
    message.yMin = object.yMin ?? 0;
    message.yMax = object.yMax ?? 0;
    return message;
  },
};

function createBasePoint(): Point {
  return { x: 0, y: 0, intensity: 0 };
}

export const Point: MessageFns<Point> = {
  encode(message: Point, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(9).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(17).double(message.y);
    }
    if (message.intensity !== 0) {
      writer.uint32(24).int32(message.intensity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Point {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePoint();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 9) {
              break;
            }

            message.x = reader.double();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.y = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.intensity = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Point {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      intensity: isSet(object.intensity) ? globalThis.Number(object.intensity) : 0,
    };
  },

  toJSON(message: Point): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.intensity !== 0) {
      obj.intensity = Math.round(message.intensity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Point>, I>>(base?: I): Point {
    return Point.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Point>, I>>(object: I): Point {
    const message = createBasePoint();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.intensity = object.intensity ?? 0;
    return message;
  },
};

function createBaseFractalResponse(): FractalResponse {
  return { points: [] };
}

export const FractalResponse: MessageFns<FractalResponse> = {
  encode(message: FractalResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.points) {
      Point.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FractalResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFractalResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.points.push(Point.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): FractalResponse {
    return { points: globalThis.Array.isArray(object?.points) ? object.points.map((e: any) => Point.fromJSON(e)) : [] };
  },

  toJSON(message: FractalResponse): unknown {
    const obj: any = {};
    if (message.points?.length) {
      obj.points = message.points.map((e) => Point.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FractalResponse>, I>>(base?: I): FractalResponse {
    return FractalResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FractalResponse>, I>>(object: I): FractalResponse {
    const message = createBaseFractalResponse();
    message.points = object.points?.map((e) => Point.fromPartial(e)) || [];
    return message;
  },
};

export interface FractalService {
  GetFractal(request: FractalRequest): Promise<FractalResponse>;
}

export const FractalServiceServiceName = "fractal.FractalService";
export class FractalServiceClientImpl implements FractalService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || FractalServiceServiceName;
    this.rpc = rpc;
    this.GetFractal = this.GetFractal.bind(this);
  }
  GetFractal(request: FractalRequest): Promise<FractalResponse> {
    const data = FractalRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetFractal", data);
    return promise.then((data) => FractalResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
